name: test

on:
  issues:
    types:
      - opened
  workflow_dispatch: # Manual trigger

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
        - uses: actions/add-to-project@v1.0.2
          with:
            project-url: https://github.com/orgs/Seeed-Studio/projects/17
            github-token: ${{ secrets.ISSUE_ASSEMBLE }}
            labeled: bug, needs-triage
            label-operator: NOT