# .github/workflows/add-to-project.yml

name: Add to GitHub Project

on:
  workflow_dispatch: # Manual trigger
  issues:
    types: [opened, edited, labeled, unlabeled]
  pull_request:
    types: [opened, edited, labeled, unlabeled]

jobs:
  add_to_project:
    runs-on: ubuntu-latest

    steps:
      - name: Add Issue or PR to Project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: 'https://github.com/orgs/Seeed-Studio/projects/17/views/1'
          github-token: ${{ secrets.ISSUE_ASSEMBLE }}
          labeled: 'bug,enhancement,question' # Replace with your desired labels
          label-operator: 'NOT' # Options: AND, OR, NOT (default is OR)